### ISSUE TITLE
プロダクション環境へのデプロイに失敗する

### ISSUE THREAD

**Issue by harachanx** [tsuemura/practical-guide-for-test-automation-support#8]
### 概要
プロダクション環境へのデプロイワークフロー（`.github/workflows/deploy_to_production.yml`）で、
Railwayへのデプロイ時に「Multiple services found.」と表示され、自動デプロイプロセスが失敗する。

### ワークフロー実行時のエラーメッセージ
```
Run railway up
Multiple services found. Please specify a service to deploy to via the `--service` flag.
Error: Process completed with exit code 1.
```

### 再現手順
1. 「 6-6-4　テストが通ることを確認する」の内容をリモートリポジトリにプッシュ
2. GitHub Actionsでプロダクション環境へのデプロイワークフローが実行される
3. `Deploy`ステップで下記エラーが発生し、デプロイが失敗する

![image](https://github.com/user-attachments/assets/37bd35b3-0d67-40c8-91ed-ef041949541e)

### 解決策
`deploy_to_production.yml`ファイルの`Deploy`ステップを以下のように更新すると正常にデプロイできる。

```yaml
- name: Deploy
  run: railway up --ci --service fastify-webapp-sample # オプションを追加
  env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
```

ちなみに、`deploy_to_staging.yml`には` --ci --service fastify-webapp-sample`が付与されているようでした。

必要であればプルリク作ります！
